version: '3'

services: 

  app:
    build: 
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    volumes: 
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true