version: '3'

services: 

  app:
    build: 
      context: .
    container_name: app-sonar
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"

  # sonarqube:
  #   image: sonarqube:latest
  #   container_name: sonarqube
  #   environment: 
  #     - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
  #   ports: 
  #     - "9000:9000"