name: Node.js CI with Sonar

on:
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15v 
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: npm test